#!/bin/bash
# Wrapper to deal with newer Ubuntu versions that don't have py2 installed
# by default.

declare -a DEPS=('apt' 'pip' 'yaml')

check_and_install() {
    if ! dpkg -s "$1" 2>&1 > /dev/null; then
        apt-get -y install "$1"
    fi
}

PYTHON="python"

check_and_install python-is-python2
for dep in ${DEPS[@]}; do
    check_and_install "${PYTHON}-${dep}"
done

exec ./hooks/install.real
