#!/bin/bash

# Wrapper to deal with newer Ubuntu versions that don't have py2 installed by
# default. Note (raychan96), the root cause of needing python2 is that
# `ud-replicate` uses `python` to do sleep function which is completely
# unnecessary. We should fix the `ud-replicate` program instead of installing
# `python` here; the `ud-replicate` is in "Bootstack Public PPA".
#
# When `ud-replicate` is fixed, delete this script, move `install.real` to
# `install`, and update hooks.py.


RELEASE=$(grep DISTRIB_RELEASE= /etc/lsb-release | sed "s/DISTRIB_RELEASE=//")

check_and_install() {
    if ! dpkg -s "$1" > /dev/null 2>&1 ; then
        apt-get -y install "$1"
    fi
}

apt-get update

if [ "$(echo "${RELEASE} > 18.04" | bc)" -eq 1 ]; then
    check_and_install python-is-python3
    PYTHON="python3"
else
    check_and_install python
    PYTHON="python"
fi

exec ./hooks/install.real
